name: prbd_tuto
description: PRBD Tutorial App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  jwt_decoder: ^2.0.1
  hive_ce: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
